<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link rel="stylesheet" href="css/index.css" />
</head>
<body>
    <?php include 'header.php' ?>
    <div class="container mt-5">
        <h1><b>Мы продаём продукты</b></h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor recusandae neque eos corporis! Ea fuga pariatur iure non culpa saepe.</p>
    </div>
    <?php include 'footer.html' ?>
</body>
</html>
